Description: cntk-keras-python3 chart
Engine: gotpl
Home: http://kuberlab.com
Icon: https://storage.googleapis.com/kuberlab/static/favicon.ico
Keywords:
- kubernets
- cntk
- keras
- python3
Maintainers:
- Email: lsheiba@kuberlab.com
  Name: Leonard Sheiba
Name: cntk-keras-py3
Version: 1.0.0
Type: mlapp
